triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: keep open
states:
    first:
        component: meya.text
        properties:
            text: "What would you like to talk about? Try 'small talk'"
            expect_user_action: true
