triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: nested
states:
    first:
        component: meya.text
        properties:
            text: "First message. Now will call subflow."
    sub:
        flow: sub
